= Learning Advanced Javascript

== Defining Functions


==== What ways can we define functions?

[source, javascript]
----
function isNimble() {
	return true;
}
var canFly = function() {
	return true;
};
window.isDeadly = function() {
	return true;
};
----


==== Does the order of function definition matter?

[source, javascript]
----
var canFly = function() {
	return true;
};

window.isDeadly = function() {
	return true;
};

assert( isNimble() && canFly() && isDeadly(), "Still works, even though isNimble is moved." );

function isNimble(){
	return true;
}
----

TIP: *PASS* Still works, even though isNimble is moved.

== Named Functions

==== We can refer to a function, within itself, by its name
[source, javascript]
----
function yell(n) {
 	return n > 0 ? yell(n-1) + "a" : "hiy";
}
assert( yell(4) == "hiyaaaa", "Calling the function by itself comes naturally." );
----

TIP: *PASS* Calling the function by itself comes naturally.

== Functions as Objects

== Context
==== How can we implement looping with a callback?
[source, javascript]
----
function loop(array, fn){
  for ( var i = 0; i < array.length; i++ ) {
    // Implement me!
  }
}
var num = 0;
loop([0, 1, 2], function(value){
  assert(value == num++, "Make sure the contents are as we expect it.");
  assert(this instanceof Array, "The context should be the full array.");
});
----



== Javascript new, constructors, and prototypes keyword

[source, javascript]
----
function Foo(){...}

var f1 = new Foo();

----


When the code new Foo(...) is executed, the following things happen:

1) A new object is created, inheriting from Foo.prototype.

2) The constructor function Foo is called with the specified arguments and `this` bound to the newly created object.

3) If the constructor function doesn't explicitly return an object, the object created in step 1 is used instead.



=== What happens when a constructor is called?

When you declare a function:

[source, javascript]
----
function Rabbit() { /* ..code.. */ }
----

1) The interpreter creates the new function object from your declaration. Together with the function, it’s `prototype` property is created and populated.

2) This default value the `prototype` is an object with property `constructor`, which is set to the function itself. In our case, to Rabbit:

`Rabbit.prototype = { constructor: Rabbit }`

3) So, when `new Rabbit` is called, the `Rabbit.prototype` becomes `__proto__` and the `constructor` becomes accessible from the object:

`rabbit.__proto__ == { constructor: Rabbit )`


=== Keeping constructor up to date

[source, javascript]
----
function Rabbit() { } // (1)
Rabbit.prototype = {}  // (2)
var rabbit = new Rabbit()
alert( rabbit.constructor == Object ) // true
----

1) In other words, when the interpreter creates a prototype of a function, it makes an object and puts `constructor` in there.

2) But the custom prototype {} is an object without constructor.

3) So, the interpreter falls back to it’s __proto__, ultimately using the native Object.prototype.constructor.

4) The constructor property is assigned to function prototype. Then the interpreter forgets about it.








